require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BaSpecsController do

  # This should return the minimal set of attributes required to create a valid
  # BaSpec. As you add validations to BaSpec, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BaSpecsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ba_specs as @ba_specs" do
      ba_spec = BaSpec.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ba_specs).should eq([ba_spec])
    end
  end

  describe "GET show" do
    it "assigns the requested ba_spec as @ba_spec" do
      ba_spec = BaSpec.create! valid_attributes
      get :show, {:id => ba_spec.to_param}, valid_session
      assigns(:ba_spec).should eq(ba_spec)
    end
  end

  describe "GET new" do
    it "assigns a new ba_spec as @ba_spec" do
      get :new, {}, valid_session
      assigns(:ba_spec).should be_a_new(BaSpec)
    end
  end

  describe "GET edit" do
    it "assigns the requested ba_spec as @ba_spec" do
      ba_spec = BaSpec.create! valid_attributes
      get :edit, {:id => ba_spec.to_param}, valid_session
      assigns(:ba_spec).should eq(ba_spec)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BaSpec" do
        expect {
          post :create, {:ba_spec => valid_attributes}, valid_session
        }.to change(BaSpec, :count).by(1)
      end

      it "assigns a newly created ba_spec as @ba_spec" do
        post :create, {:ba_spec => valid_attributes}, valid_session
        assigns(:ba_spec).should be_a(BaSpec)
        assigns(:ba_spec).should be_persisted
      end

      it "redirects to the created ba_spec" do
        post :create, {:ba_spec => valid_attributes}, valid_session
        response.should redirect_to(BaSpec.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ba_spec as @ba_spec" do
        # Trigger the behavior that occurs when invalid params are submitted
        BaSpec.any_instance.stub(:save).and_return(false)
        post :create, {:ba_spec => {}}, valid_session
        assigns(:ba_spec).should be_a_new(BaSpec)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BaSpec.any_instance.stub(:save).and_return(false)
        post :create, {:ba_spec => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ba_spec" do
        ba_spec = BaSpec.create! valid_attributes
        # Assuming there are no other ba_specs in the database, this
        # specifies that the BaSpec created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BaSpec.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ba_spec.to_param, :ba_spec => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ba_spec as @ba_spec" do
        ba_spec = BaSpec.create! valid_attributes
        put :update, {:id => ba_spec.to_param, :ba_spec => valid_attributes}, valid_session
        assigns(:ba_spec).should eq(ba_spec)
      end

      it "redirects to the ba_spec" do
        ba_spec = BaSpec.create! valid_attributes
        put :update, {:id => ba_spec.to_param, :ba_spec => valid_attributes}, valid_session
        response.should redirect_to(ba_spec)
      end
    end

    describe "with invalid params" do
      it "assigns the ba_spec as @ba_spec" do
        ba_spec = BaSpec.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BaSpec.any_instance.stub(:save).and_return(false)
        put :update, {:id => ba_spec.to_param, :ba_spec => {}}, valid_session
        assigns(:ba_spec).should eq(ba_spec)
      end

      it "re-renders the 'edit' template" do
        ba_spec = BaSpec.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BaSpec.any_instance.stub(:save).and_return(false)
        put :update, {:id => ba_spec.to_param, :ba_spec => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ba_spec" do
      ba_spec = BaSpec.create! valid_attributes
      expect {
        delete :destroy, {:id => ba_spec.to_param}, valid_session
      }.to change(BaSpec, :count).by(-1)
    end

    it "redirects to the ba_specs list" do
      ba_spec = BaSpec.create! valid_attributes
      delete :destroy, {:id => ba_spec.to_param}, valid_session
      response.should redirect_to(ba_specs_url)
    end
  end

end
